name: CI for ML project

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v3
      with:
        python-version: '3.8'
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install tensorflow  # Si no está incluido en requirements.txt
    
    - name: Run training
      run: python train.py
      
    - name: Run prediction
      run: |
        python predict.py "[13.2, 13.3]"  # Pasando datos de ejemplo para predicción (ajustar según necesidad)
        
    - name: Upload plot
      uses: actions/upload-artifact@v3
      with:
        name: training-metrics
        path: training_metrics.png  # Nombre ajustado al archivo generado

    - name: Upload prediction result
      uses: actions/upload-artifact@v3
      with:
        name: prediction-result
        path: predicho.txt
